# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGiH3XZ4d69uCQRJZ5ICt80Vkih0LD_r
"""

import streamlit as st
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

# 1. THE TITLE AND LOOK
st.set_page_config(page_title="HeartEcho AI Research", page_icon="❤️")
st.title("🫀 HeartEcho AI: Cardiac Sound Analysis")
st.write("Upload a raw heart recording to see the AI analysis.")

# 2. THE UPLOAD BUTTON
uploaded_file = st.file_uploader("Choose a heart sound file (.m4a, .wav)", type=["m4a", "wav"])

if uploaded_file is not None:
    # 3. PROCESSING (The 'Ear' of the app)
    y, sr = librosa.load(uploaded_file, sr=2000)
    y_filt = librosa.effects.preemphasis(y) # Clean the sound

    # Show the audio player so we can hear it
    st.audio(uploaded_file)

    # 4. THE VISUALS (The 'Eyes' of the app)
    st.subheader("Visual Spectrogram Analysis")
    fig, ax = plt.subplots()
    S = librosa.feature.melspectrogram(y=y_filt, sr=sr, n_mels=128)
    S_dB = librosa.power_to_db(S, ref=np.max)
    img = librosa.display.specshow(S_dB, x_axis='time', y_axis='mel', sr=sr, ax=ax)
    plt.colorbar(img, format='%+2.0f dB')
    st.pyplot(fig)

    # 5. THE AI JUDGMENT (The 'Brain' of the app)
    st.subheader("AI Diagnostic Report")
    # Simple logic for the prototype:
    high_freq = np.mean(S_dB[60:])
    if high_freq > -45:
        st.error("⚠️ Potential Abnormality Detected: High-frequency noise/murmur found.")
        st.write("Recommendation: Follow up with an Echocardiogram.")
    else:
        st.success("✅ Normal Rhythm: S1 and S2 sounds are clear and steady.")